---
'0100': Alacantí
'0200': Alcalatén
'0300': Alcoià
'0400': Alt Camp
'0500': Alt Empordà
'0600': Alt Maestrat
'0700': Alt Penedès
'0800': Alt Urgell
'0900': Alta Cerdanya
'1000': Alta Ribagorça
'1100': Alto Mijares
'1200': Alto Palancia
'1300': Alto Vinalopó
'1400': Andorra
'1500': Anoia
'1600': Bages
'1700': Baix Camp
'1800': Baix Cinca
'1900': Baix Ebre
'2000': Baix Empordà
'2100': Baix Llobregat
'2200': Baix Maestrat
'2300': Baix Penedès
'2400': Baix Vinalopó
'2600': BCN_Barcelona Vella
'2700': BCN_Eixample
'2800': BCN_Sants-Montjuïc
'2900': BCN_Les Corts
'3000': BCN_Sarrià-Sant Gervasi
'3100': BCN_Gràcia
'3200': BCN_Horta-Guinardó
'3300': BCN_Nou Barris
'3400': BCN_Sant Andreu
'3500': BCN_Sant Martí
'3600': Berguedà
'3700': Camp de Morvedre
'3800': Camp de Túria
'3900': Canal de Navarrés
'4000': Capcir
'4100': Cerdanya
'4200': Comtat
'4300': Conca de Barberà
'4400': Conflent
'4500': La Costera
'4600': Eivissa i Formentera
'4700': Fenolheda
'4800': Garraf
'4900': Garrigues
'5000': Garrotxa
'5100': Gironès
'5200': Horta
'5300': Hoya de Buñol
'5400': Llitera
'5500': Mallorca
'5600': Baix Besòs - Maresme
'5700': Marina Alta
'5800': Marina Baixa
'5900': Matarranya
'6000': Menorca
'6100': Montsià
'6200': Noguera
'6300': Osona
'6400': Pallars Jussà
'6500': Pallars Sobirà
'6600': Pla d'Urgell
'6700': Pla de l'Estany
'6800': Plana Alta
'6900': Plana Baixa
'7000': Plana de Requena-Utiel
'7100': Ports
'7200': Priorat
'7300': Baixa Ribagorça
'7400': Ribera Alta
'7500': Ribera Baixa
'7600': Ribera d'Ebre
'7700': Rincón de Ademuz
'7800': Ripollès
'7900': Rosselló
'8000': Safor
'8100': Segarra
'8200': Segrià
'8300': Selva
'8400': Serranos
'8500': Solsonès
'8600': Tarragonès
'8700': Terra Alta
'8800': Urgell
'8900': Aran
'9000': Vall d'Albaida
'9100': Valle de Ayora-Cofrentes
'9200': Vallès Occidental
'9300': Vallès Oriental
'9400': Vallespir
'9500': Valls del Vinalopó
'9600': Vega Baja
'9700': Vinalopó Medio
'9800': Moianès
'9900': Estranger i No Adscrits
