---
'3': Regió Metropolitana de Barcelona
'5819': Regió Metropolitana de Barcelona
'5820': Girona (regional)
'5821': Camp de Tarragona
'5822': Ebre
'5823': Catalunya Central
'5824': Lleida (regional)
'5825': Alt Pirineu
'5826': Penedès
'5827': Barcelona (regional)
'5828': Illes Balears i Pitiüses
'5829': País Valencià
'5830': Catalunya del Nord
'5831': Secretaria
'5832': Estranger
'13277': 2P
'14055': 2T
'15771': 2G
