default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("DB_POOL") { 5 } %>
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  username: <%= ENV.fetch("DB_USERNAME") { "" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "" } %>
  port: <%= ENV.fetch("DB_PORT") { "5432" } %>

development:
  <<: *default

test:
  <<: *default
  database: <%= ENV['DB_TEST_DATABASE'] %>

integration:
  <<: *default

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

preprod:
  <<: *default
