# i18n-tasks finds and manages missing and unused translations: https://github.com/glebm/i18n-tasks

# The "main" locale.
base_locale: ca
locales: [ca, es]
ignore_missing:
  - "decidim.proposals.proposal_endorsements_helper.render_endorsements_button_card_part.endorse"
  - "decidim.proposals.proposals.endorsements_card_row.comments"
  - decidim.account.show.*

ignore_unused:
  - "decidim.amendments.*"
  - "decidim.wizard_step_form.*"
  - "decidim.components.proposals.settings.*"
  - "decidim.proposals.models.proposal.fields.author"
